apiVersion: apps/v1
kind: Deployment
metadata:
  name: geodistancecalculator-clientapp-deployment
  labels:
    app: geodistancecalculator-clientapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geodistancecalculator-clientapp
  template:
    metadata:
      labels:
        app: geodistancecalculator-clientapp
    spec:
      containers:
      - name: geodistancecalculator-clientapp
        image: rutkowski/geodistancecalculator-clientapp:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: 128Mi
            cpu: "1"
          requests:
            memory: 64Mi
            cpu: "0.2"
