apiVersion: v1
kind: Service
metadata:
  name: geodistancecalculator-clientapp-service
spec:
  selector:
    app: geodistancecalculator-clientapp
  ports:
  - name: http-4200
    port: 4200
    targetPort: 80
  type: LoadBalancer
