apiVersion: v1
kind: Service
metadata:
  name: geodistancecalculator-webapi-service
spec:
  selector:
    app: geodistancecalculator-webapi
  ports:
  - name: http-5023
    port: 5023
    targetPort: 80
  - name: https-7023
    port: 7023
    targetPort: 443
  type: LoadBalancer
