name: Web API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore GeoDistanceCalculator.sln

    - name: Build
      run: dotnet build GeoDistanceCalculator.sln --no-restore

    - name: Test
      run: dotnet test GeoDistanceCalculator.sln /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=cobertura
        
    # Run locally: reportgenerator -reports:'**/TestResults/coverage.cobertura.xml' -targetdir:tests/TestResults/CoverageReport -reporttypes:'Badges;HtmlInline;lcov'
    - name: Generate coverage report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.0.3
      with:
        reports: '**/TestResults/coverage.cobertura.xml'
        targetdir: 'tests/TestResults/CoverageReport'
        reporttypes: 'Badges;HtmlInline;lcov'
      
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: CoverageReport        
        path: tests/TestResults/CoverageReport

    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: tests/TestResults/CoverageReport/lcov.info
